version: '3'
services:
 frontend:
  container_name: gradwohl_frontend
  build: ./frontend
  image: gradwohl_frontend
  restart: always
  ports:
    - 8080:80
  
 database:
  container_name: gradwohl_database
  image:  postgres:13-alpine
  volumes: 
   - ~/AI/Gradwohl/database/data:/var/lib/postgresql/data
  restart: always
  ports:
   - 5431:5431
  environment:
   - POSTGRES_PASSWORD=Gradwohl_Vollkornbaeckerei_Burgenland
  
 backend:
  container_name: gradwohl_backend
  image: gradwohl_backend
  build: ./backend
  restart: always
  environment:
   - server=database
   - name=postgres
   - user=postgres
   - password=gradwohl_Diplom
  ports:
   - 5050:5000
  links:
   - database
  depends_on:
   - database