# export PATH="$PATH:/Applications/Docker.app/Contents/Resources/bin"

# Container für Simon, er soll zugriff aud DB haben

version: '3'
services:
 frontend:
  container_name: gradwohl_frontend
  build: ./frontend
  image: gradwohl_frontend
  restart: always
  ports:
    - 8080:80
  
 database:
  container_name: gradwohl_database
  image: postgres:13
  volumes: 
    - ~/Spenger/Gradwohl/database/data:/var/lib/postgresql/data
  restart: always
  ports:
    - 5432:5432 
  environment:
    - POSTGRES_PASSWORD=gradwohl_Diplom
    - POSTGRES_DB= postgres
  
 backend:
  container_name: gradwohl_backend
  image: gradwohl_backend
  build: ./backend
  restart: always
  environment:
   - DB_HOST=database
   - name=postgres
   - user=postgres
   - password=gradwohl_Diplom
  ports:
   - 5050:8080
  links:
   - database
  depends_on:
   - database

 ai_python:
  container_name: gradwohl_ai
  image: gradwohl_ai
  build: ./AI
  restart: always
  ports:
   - 4000:4000
  links:
   - database
  depends_on:
   - database